project:
  type: book
  output-dir: docs
  
book:
  title: "Working with the ANO-moduler database"
  author: "Anders Kolstad"
  description: | 
    This website document how to read and write data from the postgreSQL database containing the spatial data for ANO-moduler.
  repo-url: https://github.com/NINAnor/NINA-ebook-template
  repo-branch: main
  repo-actions: [edit]
  sharing: [twitter, facebook, linkedin]
  chapters:
    - index.qmd
    - 001_connecting.qmd
    - part: "Write geographic data to the database"
      chapters: 
      - 010_SSB500.qmd
      - 011_bioclimatic_regions.qmd
    - part: "Write tabular data to the database"
      chapters: 
        - 020_samplingFrames.qmd
    - part: "Read data from database"  
      chapters: 
        - 021_readFromDb.qmd
    - part: "Spatial sampling"
      chapters:
        - 030_simulation.qmd
        - 031_wetland_sample.qmd
    
format:
  html: 
    theme: 
    - cosmo
    - NINAstyle.scss
    
    code-link: true

bibliography: references.bib
csl: NINArefStyle.csl
execute: 
  eval: false
